export const HOME_FEED_REQUEST = "HOME_FEED_REQUEST";
export const HOME_FEED_SUCCESS = "HOME_FEED_SUCCESS";
export const HOME_FEED_FAILURE = "HOME_FEED_FAILURE";
export const HOME_FEED_RELOAD = "HOME_FEED_RELOAD";

export const POST_FIELD_CHANGE = "POST_FILED_CHANGE";
export const POST_SUBMIT_REQUEST = "POST_SUBMIT_REQUEST";
export const POST_SUBMIT_SUCCESS = "POST_SUBMIT_SUCCESS";
export const POST_SUBMIT_FAILURE = "POST_SUBMIT_FAILURE";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAILURE = "POST_DETAILS_FAILURE";

export const POST_DETAILS_RESET = "POST_DETAILS_RESET";
